### PR TITLE
[B4001] Implemented the rest of the models

### PR DESCRIPTION
**Pull request by grigorem**

### CODE REVIEW

**Review by SusanLuebke — APPROVED** [review]
Completed during Pair Programming w/ Marius, Jini and Susan.

**Comment by SusanLuebke** [comment]
Approved

**Comment by SusanLuebke** [comment]
Approved

**Comment by grigorem** [comment]
[[B4001] Create an entity/model class for USER_SESSION table](https://trello.com/c/ujbArJaP/50-b4001-create-an-entity-model-class-for-usersession-table)

**Comment by grigorem** [comment]
[[B4001] Create an entity/model class for API_KEY table](https://trello.com/c/CK4vqH6W/57-b4001-create-an-entity-model-class-for-apikey-table)

**Pull request merged**
